cd /opt/odoo/account-analytic
git pull
cd /opt/odoo/account-closing
git pull
cd /opt/odoo/account-financial-reporting
git pull
cd /opt/odoo/account-financial-tools
git pull
cd /opt/odoo/account-invoicing
git pull
cd /opt/odoo/account-payment
git pull
cd /opt/odoo/bank-payment
git pull
cd /opt/odoo/bank-statement-import
git pull
cd /opt/odoo/commission
git pull
cd /opt/odoo/community-data-files
git pull
cd /opt/odoo/contract
git pull
cd /opt/odoo/crm
git pull
cd /opt/odoo/custom
git pull
cd /opt/odoo/event
git pull
cd /opt/odoo/hr
git pull
cd /opt/odoo/knowledge
git pull
cd /opt/odoo/l10n-spain
git pull
cd /opt/odoo/manufacture
git pull
cd /opt/odoo/mis-builder
git pull
cd /opt/odoo/odoo-server
git pull
cd /opt/odoo/partner-contact
git pull
cd /opt/odoo/pos
git pull
cd /opt/odoo/product-attribute
git pull
cd /opt/odoo/product-variant
git pull
cd /opt/odoo/project
git pull
cd /opt/odoo/purchase-workflow
git pull
cd /opt/odoo/queue
git pull
cd /opt/odoo/reporting-engine
git pull
cd /opt/odoo/sale-workflow
git pull
cd /opt/odoo/server-brand
git pull
cd /opt/odoo/server-tools
git pull
cd /opt/odoo/server-ux
git pull
cd /opt/odoo/social
git pull
cd /opt/odoo/stock-logistics-warehouse
git pull
cd /opt/odoo/stock-logistics-workflow
git pull
cd /opt/odoo/timesheet
git pull
cd /opt/odoo/web
git pull
cd /opt/odoo/website
git pull
