# -*- coding: utf-8 -*-
{
    'name': "/root/supermodulo",

    'summary': """
        Short (1 phrase/line) summary of the module's purpose, used as
        subtitle on modules listing or apps.openerp.com""",

    'description': """
        Long description of module's purpose
    """,

    'author': "My Company",
    'website': "http://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': [
    			 
    	'crm',
	'project',
	'stock',
	'account',
	'mrp',
	'stock_account',
	'sale_management',
	'base_address_city',
	'hr_timesheet',
	'note',
	'purchase',
	'purchase_stock',
	'hr',
	'hr_timesheet_sheet',
	'account_asset_management',
	'account_balance_line',
	'account_bank_statement_import',
	'account_banking_mandate',
	'account_banking_pain_base',
	'account_banking_sepa_credit_transfer',
	'account_banking_sepa_direct_debit',
	'account_cancel',
	'account_chart_update',
	'account_due_list',
	'account_due_list_payment_mode',
	'account_facturx',
	'account_financial_report',
	'account_invoice_constraint_chronology',
	'account_lock_date_update',
	'account_netting',
	'account_payment_mode',
	'account_payment_order',
	'account_payment_partner',
	'account_payment_purchase',
	'account_payment_sale',
	'account_payment_term_extension',
	'account_renumber',
	'account_tax_balance',
	'analytic',
	'auth_password_policy',
	'auth_password_policy_signup',
	'auth_signup',
	'barcodes',
	'base',
	'base_bank_from_iban',
	'base_iban',
	'base_import',
	'base_import_module',
	'base_location',
	'base_location_geonames_import',
	'base_setup',
	'base_technical_features',
	'base_vat',
	'board',
	'bus',
	'calendar_sms',
	'contacts',
	'crm_claim',
	'date_range',
	'decimal_precision',
	'digest',
	'disable_odoo_online',
	'document',
	'document_page',
	'document_url',
	'fetchmail',
	'iap',
	'knowledge',
	'l10n_es',
	'l10n_es_account_bank_statement_import_n43',
	'l10n_es_account_banking_sepa_fsdd',
	'l10n_es_account_invoice_sequence',
	'l10n_es_aeat',
	'l10n_es_aeat_mod111',
	'l10n_es_aeat_mod115',
	'l10n_es_aeat_mod303',
	'l10n_es_aeat_mod347',
	'l10n_es_aeat_mod349',
	'l10n_es_aeat_mod390',
	'l10n_es_mis_report',
	'l10n_es_partner',
	'l10n_es_toponyms',
	'l10n_es_vat_book',     
        'l10n_es_account_asset',
	'mail',
	'mail_activity_board',
	'mail_bot',
	'mass_editing',
	'mis_builder',
	'partner_autocomplete',
	'payment',
	'payment_transfer',
	'procurement_jit',
	'product',
	'project_description',
	'project_task_add_very_high',
	'project_task_default_stage',
	'project_template',
	'project_timeline',
	'project_timeline_hr_timesheet',
	'purchase_mrp',
	'rating',
	'report_xlsx',
	'resource',
	'sale',
	'sale_crm',
	'sale_mrp',
	'sale_purchase',
	'sale_stock',
	'sale_timesheet',
	'sales_team',
	'sms',
	'snailmail',
	'snailmail_account',
	'social_media',
	'uom',
	'utm',
	'web',
	'web_decimal_numpad_dot',
	'web_diagram',
	'web_editor',
	'web_export_view',
	'web_kanban_gauge',
	'web_no_bubble',
	'web_responsive',
	'web_settings_dashboard',
	'web_timeline',
	'web_tour',
	'web_unsplash',
	'web_widget_color',
	'web_widget_x2many_2d_matrix',
	'mass_mailing',
	'calendar',
	'portal',
	'http_routing',
	'phone_validation',
    ],

    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}
