# -*- coding: utf-8 -*-
{
    'name': "/root/supermodulo",

    'summary': """
        Short (1 phrase/line) summary of the module's purpose, used as
        subtitle on modules listing or apps.openerp.com""",

    'description': """
        Long description of module's purpose
    """,

    'author': "My Company",
    'website': "http://www.yourcompany.com",

    # Categories can be used to filter modules in modules listing
    # Check https://github.com/odoo/odoo/blob/12.0/odoo/addons/base/data/ir_module_category_data.xml
    # for the full list
    'category': 'Uncategorized',
    'version': '0.1',

    # any module necessary for this one to work correctly
    'depends': [
    			 
    	'account',
	'account_asset_management',
	'account_balance_line',
	'account_bank_statement_import',
	'account_banking_mandate',
	'account_banking_pain_base',
	'account_banking_sepa_credit_transfer',
	'account_banking_sepa_direct_debit',
	'account_chart_update',
	'account_due_list',
	'account_due_list_payment_mode',
	'account_facturx',
	'account_financial_report',
	'account_invoice_search_by_reference',
	'account_invoice_supplier_ref_unique',
	'account_lock_date_update',
	'account_move_force_removal',
	'account_move_template',
	'account_netting',
	'account_payment',
	'account_payment_mode',
	'account_payment_order',
	'account_payment_partner',
	'account_payment_purchase',
	'account_payment_purchase_stock',
	'account_payment_sale',
	'account_payment_term_extension',
	'account_tax_balance',
	'analytic',
	'attachment_indexation',
	'auth_signup',
	'barcodes',
	'base',
	'base_address_city',
	'base_bank_from_iban',
	'base_iban',
	'base_import',
	'base_import_module',
	'base_location',
	'base_location_geonames_import',
	'base_partner_sequence',
	'base_setup',
	'base_technical_features',
	'base_vat',
	'board',
	'bus',
	'calendar',
	'calendar_sms',
	'contacts',
	'crm',
	'crm_claim',
	'crm_sms',
	'date_range',
	'delivery',
	'digest',
	'disable_odoo_online',
	'document_page',
	'document_page_project',
	'document_url',
	'fetchmail',
	'hr',
	'hr_org_chart',
	'http_routing',
	'iap',
	'knowledge',
	'l10n_es',
	'l10n_es_account_asset',
	'l10n_es_account_bank_statement_import_n43',
	'l10n_es_account_banking_sepa_fsdd',
	'l10n_es_aeat',
	'l10n_es_aeat_mod111',
	'l10n_es_aeat_mod115',
	'l10n_es_aeat_mod303',
	'l10n_es_aeat_mod347',
	'l10n_es_mis_report',
	'l10n_es_partner',
	'l10n_es_toponyms',
	'l10n_es_vat_book',
	'mail',
	'mail_bot',
	'mass_editing',
	'mass_operation_abstract',
	'mis_builder',
	'mis_builder_budget',
	'mis_builder_cash_flow',
	'note',
	'odoo_referral',
	'partner_autocomplete',
	'partner_label',
	'partner_statement',
	'payment',
	'payment_transfer',
	'phone_validation',
	'portal',
	'procurement_jit',
	'product',
	'project',
	'project_description',
	'project_tag',
	'project_task_add_very_high',
	'project_task_default_stage',
	'project_template',
	'project_timeline',
	'purchase',
	'purchase_stock',
	'rating',
	'remove_odoo_enterprise',
	'report_batch',
	'report_xlsx',
	'resource',
	'sale',
	'sale_crm',
	'sale_force_invoiced',
	'sale_management',
	'sale_purchase',
	'sale_stock',
	'sales_team',
	'sms',
	'snailmail',
	'snailmail_account',
	'stock',
	'stock_account',
	'stock_sms',
	'uom',
	'utm',
	'web',
	'web_decimal_numpad_dot',
	'web_diagram',
	'web_editor',
	'web_kanban_gauge',
	'web_no_bubble',
	'web_responsive',
	'web_timeline',
	'web_tour',
	'web_unsplash',
    ],

    # always loaded
    'data': [
        # 'security/ir.model.access.csv',
        'views/views.xml',
        'views/templates.xml',
    ],
    # only loaded in demonstration mode
    'demo': [
        'demo/demo.xml',
    ],
}
